# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-18.04    #ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: copy to tmp
      run: cp /home/runner/work/addressbook/addressbook/target/addressbook-2.0.war /tmp/addressbook.war

    - name: list tmp folder
      run: ls -al /tmp

    - name: Build and push updated
      run: |
        #echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "mmdeniz" --password-stdin
        docker image build -t mmdeniz/addressbookGA:v${{ BUILD_NUMBER }} .
        docker push mmdeniz/addressbookGA:v${{ BUILD_NUMBER }}
    
    
    
    
      #uses: docker/build-push-action@v3
      #with:
      #  context: "{{defaultContext}}:df"
      #  push: true
      #  tags: mmdeniz/addressbook-github-actions-push:latest
      #  #cache-from: type=local,src=/tmp/.buildx-cache
      #  #cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
